### ISSUE TITLE
After updating the plugin, homebridge cannot see the plugin

### ISSUE THREAD

**Issue by dmike3** [jvmahon/Homebridge-HomeSeer4#165]
====================
[1/3/2022, 10:37:55 AM] ERROR LOADING PLUGIN homebridge-homeseer4:
[1/3/2022, 10:37:55 AM] /usr/lib/node_modules/homebridge-homeseer4/lib/HomeSeerSystemObject.js:133
                return this.HomeSeerDevices[reference]?.ControlPairs.find( function(currentElement) { 
                                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-homeseer4/index.js:16:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[1/3/2022, 10:37:55 AM] ====================
[1/3/2022, 10:37:55 AM] Loading 3 platforms...
[1/3/2022, 10:37:55 AM] No plugin was found for the platform "HomeSeer" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by jvmahon** [comment]
Update node to at least version 14.5

I've now published a new version 1.0.24 which will warn if you don't have this version of node or later installed.
