### ISSUE TITLE
MultilevelFan error with v1.0.25

### ISSUE THREAD

**Issue by RB72** [jvmahon/Homebridge-HomeSeer4#172]
Hi,
With version 1.0.24 everything was working fine. After upgrading to 1.0.25 I got the following error message:

/usr/lib/node_modules/homebridge-homeseer4/lib/DeviceDefaults.js:522
                                throw new SyntaxError(error);
          ^
SyntaxError: config.json error: property: levels is not a valid property for item named: Woonkamer Afzuiging of type: MultilevelFan. 
Valid Properties for this type are: type,name,ref,uuid_base,interface_name,onValue,offValue,batteryRef,batteryThreshold.
    at Object.hasValidProperties (/usr/lib/node_modules/homebridge-homeseer4/lib/DeviceDefaults.js:522:11)
    at /usr/lib/node_modules/homebridge-homeseer4/lib/HomeSeerUtilities.js:157:18
    at Array.forEach (<anonymous>)
    at Object.checkConfig (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeSeerUtilities.js:60:22)
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:119:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

This is the json-config part:

{
                    "type": "Fan",
                    "name": "Woonkamer Afzuiging",
                    "ref": 361,
                    "uuid_base": "Ref361.0",
                    "onValue": 3,
                    "offValue": 0,
                    "levels": 3
}

**Comment by jvmahon** [comment]
Yeah, I know what went wrong. I'll fix that within a day or so.

**Comment by RB72** [comment]
Great, thanks!

**Comment by jvmahon** [comment]
Try 1.0.26 and let me know if that works.
Thanks.

**Comment by RB72** [comment]
Nope, new error:

[16-5-2022 15:43:10] ====================
[16-5-2022 15:43:10] ERROR LOADING PLUGIN homebridge-homeseer4:
[16-5-2022 15:43:10] /usr/lib/node_modules/homebridge-homeseer4/lib/DeviceDefaults.js:299
                        "levels": 99,,
                                     ^

SyntaxError: Unexpected token ','
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeSeerUtilities.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
[16-5-2022 15:43:10] ====================

**Comment by jvmahon** [comment]
Ugh. typo. Try 1.0.27.
If that doesn't work, then I'll have to try it from home.

**Comment by RB72** [comment]
v1.0.27 gave another new error:

/usr/lib/node_modules/homebridge-homeseer4/lib/Setup Valve.js:29
        thisService
 ^
ReferenceError: thisService is not defined
    at Object.exports.setupValves (/usr/lib/node_modules/homebridge-homeseer4/lib/Setup Valve.js:29:2)
    at Object.exports.setupServices (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:94:11)
    at HomeSeerAccessory.getServices (/usr/lib/node_modules/homebridge-homeseer4/index.js:161:11)
    at BridgeService.createHAPAccessory (/usr/lib/node_modules/homebridge/src/bridgeService.ts:461:41)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:549:34
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:539:21
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:131:3)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by jvmahon** [comment]
1.0.28
Sorry about these little bugs - I made a lot of code changes so that the code is easier to maintain. However, as I don't use HomeSeer anymore, I could not fully test it.

**Comment by RB72** [comment]
Yes, this version is working fine again, thank you.
And thanks for the continuous work on this plugin, appreciate it!

**Comment by jvmahon** [comment]
You're welcome. Thanks for your feedback / help in testing this.
