### ISSUE TITLE
Latest version causes homebridge to continually crash

### ISSUE THREAD

**Issue by tundrageek-AK** [jvmahon/Homebridge-HomeSeer4#174]
Hello. I just updated the plugin to the latest version and now it's causing homebridge to continually crash after logging this error:

[5/16/2022, 8:36:04 AM] Initializing platform accessory 'Garage Door'...
[5/16/2022, 8:36:04 AM] ReferenceError: LocksDoorswindows is not defined
    at Object.exports.setupServices (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:103:4)
    at HomeSeerAccessory.getServices (/usr/lib/node_modules/homebridge-homeseer4/index.js:161:11)
    at BridgeService.createHAPAccessory (/usr/lib/node_modules/homebridge/src/bridgeService.ts:461:41)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:549:34
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:539:21
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:131:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by tundrageek-AK** [comment]
I installed the older version 1.0.24 to restore functionality until the issue with the latest can be looked at.

**Comment by jvmahon** [comment]
Yep. A typo. Try 1.0.29

**Comment by tundrageek-AK** [comment]
Thank you. 1.0.29 installed and stable.
