### ISSUE TITLE
Existing WiFi thermostat broken by new Nest functionality?

### ISSUE THREAD

**Issue by jradwan** [jvmahon/Homebridge-HomeSeer4#191]
Just upgraded to 1.0.36 of the plugin and now it keeps restarting over and over. Seems to be an issue with the plugin "detecting" my thermostat (which is NOT a Nest) and failing. This was all working fine with the prior version. From the  log:

```
[27/10/2022, 22:48:39] [HomeSeer] Launched child bridge with PID 31565
homebridge API version: 2.7
[27/10/2022, 22:48:39] Registering platform 'homebridge-homeseer4.HomeSeer'
[27/10/2022, 22:48:39] [HomeSeer] Loaded homebridge-homeseer4 v1.0.36 child bridge successfully
[27/10/2022, 22:48:40] Loaded 0 cached accessories from cachedAccessories.0E2DD88BB2ED.
[27/10/2022, 22:48:40] [HomeSeer] Start
[27/10/2022, 22:48:40] [HomeSeer] End
Creating HomeKit devices from HomeSeer data.
[27/10/2022, 22:48:40] [HomeSeer] Checking Configuration Data
[27/10/2022, 22:48:40] Initializing platform accessory 'Garage Overhead Door'...
[27/10/2022, 22:48:40] Initializing platform accessory 'Kitchen Sink Lights'...
[27/10/2022, 22:48:41] Initializing platform accessory 'Master Bedroom Light'...
[27/10/2022, 22:48:41] Initializing platform accessory 'Foyer Lock'...
[27/10/2022, 22:48:41] Initializing platform accessory 'Foyer Lock'...
[27/10/2022, 22:48:41] Initializing platform accessory 'Hallway Thermostat'...
[27/10/2022, 22:48:41] [HomeSeer] Thermostat identified by a root device. Attempting to automatically determine its parameters.
[27/10/2022, 22:48:41] [HomeSeer] *Warning* - Found a Temperature device of Type 16, Subtype:0 but device is not using the 'Nest' thermostat plugin. Setting of 'ref' value may be incorrect. You may need to use the 'complex' configuration procedure. Please report this as an issue on github so a correction can be made. Also see wiki entry on Thermostats for additional information. Interface name is: Honeywell WiFi Thermostat
[27/10/2022, 22:48:41] [HomeSeer] *Warning* - Found a Temperature device of Type 16, Subtype:0 but device is not using the 'Nest' thermostat plugin. Setting of 'ref' value may be incorrect. You may need to use the 'complex' configuration procedure. Please report this as an issue on github so a correction can be made. Also see wiki entry on Thermostats for additional information. Interface name is: Honeywell WiFi Thermostat
[27/10/2022, 22:48:41] [HomeSeer] Setting up a Thermostat with configuration values: {"controlRef":264,"stateRef":265,"ref":273,"humidityRef":272,"coolingSetpointRef":274,"heatingSetpointRef":275}

/usr/lib/node_modules/homebridge-homeseer4/lib/Setup Thermostat.js:188
                                        throw new RangeError("Error setting up Thermostat. Scale is not Celsius or Fahrenheit"); 
           ^
RangeError: Error setting up Thermostat. Scale is not Celsius or Fahrenheit
    at Object.exports.setupThermostat (/usr/lib/node_modules/homebridge-homeseer4/lib/Setup Thermostat.js:188:12)
    at Object.exports.setupServices (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:79:16)
    at HomeSeerAccessory.getServices (/usr/lib/node_modules/homebridge-homeseer4/index.js:165:11)
    at BridgeService.createHAPAccessory (/usr/lib/node_modules/homebridge/src/bridgeService.ts:461:41)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:549:34
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:539:21
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at HomeSeerPlatform.accessories (/usr/lib/node_modules/homebridge-homeseer4/index.js:135:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[27/10/2022, 22:48:41] [HomeSeer] Child bridge process ended
[27/10/2022, 22:48:41] [HomeSeer] Process Ended. Code: 1, Signal: null
[27/10/2022, 22:48:48] [HomeSeer] Restarting Process...
[27/10/2022, 22:48:51] [HomeSeer] Launched child bridge with PID 31599
```

**Comment by jradwan** [comment]
Ok, might have created an issue too soon. Following the wiki, I switched from the Simple config to the Advanced config for my Honeywell thermostat, manually setting the correct Ref and filling in the rest. That seemed to fix it.

```
        {
            "type": "Thermostat",
            "name": "Thermostat",
            "ref": 269,
            "controlRef": 264,
            "stateRef": 265,
            "heatingSetpointRef": 275,
            "coolingSetpointRef": 274,
            "humidityRef": 272
        }
```

**Comment by jvmahon** [comment]
OK, glad you got it to work. Closing this out then.
