### ISSUE TITLE
Front Gate reporting as Locked when it should be Unlocked

### ISSUE THREAD

**Issue by alexwoolfson** [jvmahon/Homebridge-HomeSeer4#33]
Hello,

I got an Apple Watch for Xmas so I wanted to connect my HomeSeer to HomeKit. I used the new Homebridge HS4 plugin here, and I'm pleased to say, everything worked well and I was able to get things running just great on my Windows NUC Homeseer setup. Thank you so much for the awesome plugin and wiki instructions!

I have run into only one issue, and while I expect it's a simple one to fix, I'm just running into a wall and I could use some help.

I use a Z-Wave relay to unlock my gate. When I turn it on, it opens the circuit for 5 seconds, "buzzing" the gate open during that period. Then it turns itself back off.

I listed its Device Number under Locks in the Homebridge config file.

The good news is that I can use it with Homekit just as easily as with Homeseer. The bad news is that, since its default state is off, it's showing as Unlocked in HomeKit, when it is, in fact, locked.

I'm sure I just need to change the status reporting somehow, but what I've tried hasn't worked.

Here is it correctly showing in HomeSeer:

<img width="998" alt="2020-01-03_13-54-23" src="https://user-images.githubusercontent.com/1188997/71757898-5664e100-2e4e-11ea-8844-35d190527868.png">

This, unfortunately, is what I am seeing for the same status in HomeKit:

<img width="231" alt="2020-01-03_13-56-03" src="https://user-images.githubusercontent.com/1188997/71757891-4e0ca600-2e4e-11ea-8eac-ab7db1850ac3.png">

And this is what I have for the Status Text/Graphics for the Front Gate relay device in HS3:

<img width="1004" alt="2020-01-03_17-28-06" src="https://user-images.githubusercontent.com/1188997/71757906-72688280-2e4e-11ea-8ca4-5bf06ba4b64f.png">

Do you have any idea what I would need to change to get HomeKit to see 0 as "Locked" and 255 as "Unlocked"? Any help would be greatly appreciated.

Thanks!

Alex

**Comment by dibble9012** [comment]
I'm guessing you have set up in a simplified config file. Try setting it up as a complex one.


{
"type": "Lock",
"name":Gate,
"ref": 108,
"lockValue":0,
"unlockValue": 255,	
},

**Comment by alexwoolfson** [comment]
Thank you. I will try that! :)

Will I just need to add that code for that one device in the accessories section? Or will I need to create code like that for every single device in accessories, now that my config file will be "complex."

Also, can I give it any Name I want, like Front Gate? Or should I keep it to one word like you have it?

**Comment by jvmahon** [comment]
As I mentioned on the HomeSeer forum, you should have been able to just do this by setting the "Control Use" field.

However, when you said it didn't work, I took a look at the code and there is a bug that needs to be fixed. 

If you can wait until tomorrow (Sunday at the latest), I'll have it fixed and then the "Control Use" method will work for you.
Look for a version 0.0.32 to be released.

**Comment by alexwoolfson** [comment]
Oh! I can definitely wait until Sunday, and then I can at least let you know if that bug has been squashed. 

Thank you!

**Comment by jvmahon** [comment]
Updated to plugin version 0.0.33 and set the "Control Use" fields on the Status Graphics page to "Door Lock" and "Door Unlock" instead of "Not Specified".

Let me know if this now works as expected.

And you should be able to use the "Simplified" configuration setup method.
Regards,
JVM

**Comment by alexwoolfson** [comment]
Howdy JVM,

Thank you very much for the quick turnaround.  

I am using Homebridge Config UI X (v 4.6.7) and used it to upgrade Homebridge Homeseer 4 to 0.0.33. The upgrade was successful, but I didn't notice any change in the Gate status in Homekit on my iPhone. I tried restarting Homebridge, but the restart timed out. I tried restarting my NUC, and again, Homebridge seemed to hang at launch and none of my accessories were responding in HomeKit.

Checking the logs, I found that Homebridge was actually stuck in a loop. I've copied the loop that kept repeating in the logs below. It looks like something with the Gate lockedStatusValues is now flipping it out, and so Homebridge keeps restarting itself.

Here is the log:

```
[1/4/2020, 12:21:45 AM] [HB Supervisor] Restarting Homebridge...
[1/4/2020, 12:21:45 AM] [HB Supervisor] Started Homebridge with PID: 10120
[1/4/2020, 12:21:45 AM] Loaded config.json with 0 accessories and 2 platforms.
[1/4/2020, 12:21:45 AM] ---
[1/4/2020, 12:21:45 AM] Loaded plugin: homebridge-config-ui-x
[1/4/2020, 12:21:45 AM] Registering platform 'homebridge-config-ui-x.config'
[1/4/2020, 12:21:45 AM] ---
[1/4/2020, 12:21:45 AM] Loaded plugin: homebridge-homeseer4
homebridge API version: 2.4
[1/4/2020, 12:21:45 AM] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[1/4/2020, 12:21:45 AM] ---
[1/4/2020, 12:21:45 AM] Loading 2 platforms...
[1/4/2020, 12:21:45 AM] [Config] Initializing config platform...
[1/4/2020, 12:21:45 AM] [Config] Running in Standalone Mode.
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing HomeSeer platform...
[1/4/2020, 12:21:45 AM] Loading 0 accessories...
Load homebridge-HomeSeerPlatform.HomeSeer
[1/4/2020, 12:21:45 AM] [HomeSeer] Checking Configuration Data
[1/4/2020, 12:21:45 AM] [HomeSeer] Added a battery to device#: 55
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Bathroom Bathroom Light '...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Bedroom Bedroom Overhead Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Bedroom Closet Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Foyer Foyer Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Hallway Hall Light '...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Kitchen Kitchen Table Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Laundry Room Laundry Room Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Office Office Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Bedroom Floor Lamp'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Living Room Living Room Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Kitchen Kitchen Overhead Light'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Front Door Schlage Door Lock'...
[1/4/2020, 12:21:45 AM] [HomeSeer] Initializing platform accessory 'Front Door Front Gate'...
(node:10120) UnhandledPromiseRejectionWarning: SyntaxError: *ERROR* - Error setting up lock. The unlockedS
tatusValues includes your locking value, or else the lockedStatusValues inlcudes your unlocking value. Please report this on github if you can't resolve it!
    at Object.exports.setupServices (C:\Users\order\AppData\Roaming\npm\node_modules\homebridge-homeseer4\
lib\HomeKitDeviceSetup.js:1127:13)
    at HomeSeerAccessory.getServices (C:\Users\order\AppData\Roaming\npm\node_modules\homebridge-homeseer4
\index.js:407:11)
    at Server._createAccessory (C:\Users\order\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:4
27:36)
    at Server.<anonymous> (C:\Users\order\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:413:32
)
    at C:\Users\order\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js
:16:19
    at C:\Users\order\AppData\Roaming\npm\node_modules\homebridge-homeseer4\index.js:365:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/4/2020, 12:21:45 AM] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null
```

Please let me know if you need anything else to troubleshoot this. Thanks!

**Comment by jvmahon** [comment]
Update to 0.0.34 and try again.
Thanks.

**Comment by alexwoolfson** [comment]
Thank you! That worked great. All the events are working and the Gate is reporting properly. The logs give me a little complaint about my door lock:

```
[1/4/2020, 10:35:50 AM] [HomeSeer] Initializing platform accessory 'Front Door Schlage Door Lock'...
[1/4/2020, 10:35:50 AM] [HomeSeer] *Warning* - You have not specified an unlockValue for device '55' and the 'Control Use' setting on the HomeSeer 'Status Graphics' page for this device is not set to 'Door Unlock' so taking a wild guess that the unlockValue is 0.
[1/4/2020, 10:35:50 AM] [HomeSeer] *Warning* - You have not specified a lockValue for device '55' and the 'Control Use' setting on the HomeSeer 'Status Graphics' page for this device is not set to 'Door lock' so taking a wild guess that the lockValue is 255.
```
but since that's working fine, I probably won't mess with my current set-up.  I can see why you would add that warning as a troubleshooting tool for anyone else who runs into a similar issue to what I ran into.

So, again, thank you very much for you help and the quick turnaround on all of this!

**Comment by jvmahon** [comment]
Did you set the "control use" field on the HomeSeer Status Graphics page to Door Lock and Door Unlock?  If you did, then this warning should not have displayed. If that's the case, I'll take another look and correct it. I expect to publish a new version tonight to correct a problem with Nest thermostats and I can include this in the update if there is still an issue.

Let me know. Thanks.
Jim

**Comment by alexwoolfson** [comment]
Howdy Jim,

This is actually a separate device than the Gate I was having issues with. It's a door lock that has actually been reporting properly in HomeKit all along. Since I never had any issues with it, I've kept it at the default settings it installed with:

<img width="1095" alt="2020-01-05_11-02-29" src="https://user-images.githubusercontent.com/1188997/71784706-1109f600-2fab-11ea-844a-42eb3f502af8.png">

I never set the "control use" of this door lock device to anything. And since it isn't broken, I'm hesitant to change anything unless you strongly feel I should. 

So, I don't think you need to change anything with your plugin. I think that warning in the logs makes sense (in case someone does run into a problem.) And I'm not getting that warning with my Gate device (where I did set the control use.)

Cheers,

Alex

**Comment by jvmahon** [comment]
O.K., now I understand.
I also have Schlage door locks and when I added mine to HomeSeer, HomeSeer automatically set the Control Use to the Door Locked / Door Unlocked values.   I suspect you may have added them using a different version of the HomeSeer Z-wave plugin and that some versions of the plugin didn't set the setting correct.  My suggestion is to fix the Control Use values, but that's your call.  In any case, it seems the plugin issue is resolved so I'll close this issue.
