### ISSUE TITLE
Error during plugin start.

### ISSUE THREAD

**Issue by RienduPre** [jvmahon/Homebridge-HomeSeer4#48]
Hi,

Installed HS4 Pro Edition 4.0.1.23 (Windows)
Latest Homebridge 4.50 (docker)
Latest HomeSeer4 plugin 0.0.43

And get this error, any idea what might cause this?

[2/8/2020, 3:52:44 PM] Loaded config.json with 0 accessories and 2 platforms.
[2/8/2020, 3:52:44 PM] ---
[2/8/2020, 3:52:44 PM] Loaded plugin: homebridge-dummy
[2/8/2020, 3:52:44 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[2/8/2020, 3:52:44 PM] ---
[2/8/2020, 3:52:45 PM] Loaded plugin: homebridge-homeseer4
homebridge API version: 2.4
[2/8/2020, 3:52:45 PM] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[2/8/2020, 3:52:45 PM] ---
[2/8/2020, 3:52:45 PM] Loaded plugin: homebridge-config-ui-x
[2/8/2020, 3:52:45 PM] Registering platform 'homebridge-config-ui-x.config'
[2/8/2020, 3:52:45 PM] ---
[2/8/2020, 3:52:45 PM] Loading 2 platforms...
[2/8/2020, 3:52:45 PM] [Config] Initializing config platform...
[2/8/2020, 3:52:45 PM] [Config] Running in Standalone Mode.
[2/8/2020, 3:52:45 PM] [HomeSeer] Initializing HomeSeer platform...
[2/8/2020, 3:52:45 PM] [HomeSeer] Start
[2/8/2020, 3:52:45 PM] Loading 0 accessories...
Load homebridge-HomeSeerPlatform.HomeSeer
[2/8/2020, 3:52:45 PM] [HomeSeer] End
Creating HomeKit devices from HomeSeer data.
[2/8/2020, 3:52:45 PM] [HomeSeer] Checking Configuration Data
(node:3676) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at HomeSeerPlatform.accessories (/homebridge/node_modules/homebridge-homeseer4/index.js:165:74)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:3676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

config.json
{
    "bridge": {
        "name": "HB-Docker-1",
        "username": "12345",
        "port": 51826,
        "pin": "478-23613350",
        "model": "Homebridge",
        "serialNumber": "4.0"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "teal",
            "tempUnits": "c",
            "log": {
                "method": "file",
                "path": "/logs/homebridge.log"
            },
            "platform": "config"
        },
        {
            "platform": "HomeSeer",
            "name": "HomeSeer",
            "host": "http://192.168.0.1",
            "login": "userid",
            "password": "password",
            "Fans": [],
            "GaragedDoorOpeners": [],
            "Lightbulbs": [],
            "Locks": [],
            "Thermostats": [],
            "Outlets": [],
            "Switches": [],
            "Windows": [],
            "WindowCoverings": [],
            "CarbonDioxideSensors": [],
            "CarbonMonoxideSensors": [],
            "ContactSensors": [],
            "HumiditySensors": [],
            "LeakSensors": [],
            "LightSensors": [],
            "MotionSensors": [],
            "OccupancySensors": [],
            "SmokeSensors": [],
            "TemperatureSensors": [],
            "Valves": [],
            "SecuritySystems": [],
            "accessories": [
                {
                    "type": "Lock",
                    "ref": 640
                }
            ]
        }
    ]
}

**Comment by jvmahon** [comment]
It looks like you haven't added any accessories of your own and the only thing in there is a lock which has the same reference number as the one I had in the example file.

**Comment by jvmahon** [comment]
[config.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4174914/config.zip)

I suggest you simplify your config file down to a single platform and only add one or two lightbulbs to start. Get that working, then add the rest of your devices.  See the attached simplified config.json. Of course, you'd have to add the ip address of your HomeSeer system and the correct HomeSeer reference numbers for your devices.

**Comment by RienduPre** [comment]
Fixed it, sorry to bother you.....
