### ISSUE TITLE
Error starting homebridge

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#52]
I updated node, I think it may have caused this. Node v 13.8

homeseer4 plugin:
`Feb 13 02:32:31 DibDabsPi homebridge[5991]: (node:5991) UnhandledPromiseRejectionWarning: TypeError: getStatusInfo.Devices is not iterable
Feb 13 02:32:31 DibDabsPi homebridge[5991]:     at HomeSeerSystem.initialize (/opt/nodejs/lib/node_modules/homebridge-homeseer4/lib/HomeSeerSystemObject.js:447:42)
Feb 13 02:32:31 DibDabsPi homebridge[5991]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Feb 13 02:32:31 DibDabsPi homebridge[5991]:     at async HomeSeerPlatform.accessories (/opt/nodejs/lib/node_modules/homebridge-homeseer4/index.js:95:24)
Feb 13 02:32:31 DibDabsPi homebridge[5991]: (node:5991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Feb 13 02:32:31 DibDabsPi homebridge[5991]: (node:5991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

homeseer-2018 plugin

`Feb 13 02:34:11 DibDabsPi homebridge[6132]: [13/02/2020, 02:34:11] [HomeSeer] Checking Configuration Data
Feb 13 02:34:11 DibDabsPi homebridge[6132]: [13/02/2020, 02:34:11] [HomeSeer] Cannot read property 'findIndex' of undefined`

**Comment by dibble9012** [comment]
Disregard this. I had the wrong port typed in the config file.
