### ISSUE TITLE
LOST: Homebridge service will not start and cryptic error

### ISSUE THREAD

**Issue by ando01** [jvmahon/Homebridge-HomeSeer4#57]
My homebridge instance just stooped working and I am getting a cryptic message I do not understand. I tried some Goolge Fu but am not coming up with anything.

Here is the error message in the logs:

```
Load homebridge-HomeSeerPlatform.HomeSeer
Failed to find plugin to handle accessory FAMILY ROOM THERMOSTAT
Failed to find plugin to handle accessory Basement BathRm
Failed to find plugin to handle accessory Office
Failed to find plugin to handle accessory Basement
Failed to find plugin to handle accessory DINING ROOM THERMOSTAT
Failed to find plugin to handle accessory WillsGamePC
Failed to find plugin to handle accessory Andrews MacBook Air
[3/22/2020, 3:11:48 PM] [Sonos] restored 5 accessories from cache
[3/22/2020, 3:11:48 PM] Garage is running on port 44815.
[3/22/2020, 3:11:48 PM] Please add [Garage] manually in Home app. Setup Code: 032-45-155
[3/22/2020, 3:11:48 PM] Driveway 1 is running on port 38291.
[3/22/2020, 3:11:48 PM] Please add [Driveway 1] manually in Home app. Setup Code: 032-45-155
[3/22/2020, 3:11:48 PM] Driveway2 is running on port 32977.
[3/22/2020, 3:11:48 PM] Please add [Driveway2] manually in Home app. Setup Code: 032-45-155
[3/22/2020, 3:11:48 PM] Back Yard is running on port 36551.
[3/22/2020, 3:11:48 PM] Please add [Back Yard] manually in Home app. Setup Code: 032-45-155
[3/22/2020, 3:11:48 PM] [Sonos] listening on http://192.168.9.156:45121/notify
[3/22/2020, 3:11:48 PM] [Sonos] RINCON_5CAAFDF8F96C01400 [Family Room]: associated zone player
[3/22/2020, 3:11:48 PM] [HomeSeer] End
Creating HomeKit devices from HomeSeer data.
[3/22/2020, 3:11:48 PM] [HomeSeer] Checking Configuration Data
(node:1108) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at HomeSeerPlatform.accessories (/usr/local/lib/node_modules/homebridge-homeseer4/index.js:165:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by jvmahon** [comment]
I haven't seen this happen before.  If a reboot of HomeSeer and HomeBridge doesn't work, you might have to reset (delete) the homebridge database and pair it again. See Section F, here, https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Windows-10-Installation

**Comment by ando01** [comment]
Thanks. Luckily this is a VM and I had a recent snapshot from a month ago. I restored the snap and all is working again.
