### ISSUE TITLE
Cant get plugin to load

### ISSUE THREAD

**Issue by vegargrim** [jvmahon/Homebridge-HomeSeer4#70]
Hello, im having problems adding homeseer to homebridge. I am using the official homebridge image and homeseer version HS3 (3.0.0.500).

This is my config.json
```
{
	"bridge": {
		"name": "Homebridge 62D7",
		"username": "0E:1A:94:22:62:D7",
		"port": 51100,
		"pin": "660-57-813"
	},
	"platforms": [
    {
		  "platform": "HomeSeer",
		  "name": "HomeSeer",
		  "host": "IPADRESS",
		  "ASCIIPort": 11000,
		  "login":"username",
		  "password":"password",
		  "accessories": [
				{
					"type": "DimmingLight",
					"ref": 279,
					"onValue": 99,
					"offValue": 0
    		}
  		]
		}
	]
}

```

But, when I try to start homebridge I get this message
```
[5/6/2020, 18:46:59] Loaded config.json with 0 accessories and 1 platforms.
[5/6/2020, 18:46:59] ---
[5/6/2020, 18:47:00] Loaded plugin: homebridge-config-ui-x
[5/6/2020, 18:47:00] Registering platform 'homebridge-config-ui-x.config'
[5/6/2020, 18:47:00] ---
[5/6/2020, 18:47:00] Loaded plugin: homebridge-homeseer4
homebridge API version: 2.5
[5/6/2020, 18:47:00] Registering platform 'homebridge-homeseer4.HomeSeer'
[5/6/2020, 18:47:00] ---
[5/6/2020, 18:47:00] Loading 1 platforms...
[5/6/2020, 18:47:00] [HomeSeer] Initializing HomeSeer platform...
[5/6/2020, 18:47:00] [HomeSeer] Start
[5/6/2020, 18:47:01] [HomeSeer] End
Creating HomeKit devices from HomeSeer data.
[5/6/2020, 18:47:01] [HomeSeer] Checking Configuration Data
[5/6/2020, 18:47:01] Initializing platform accessory 'Stue Taklys Stue'...
[5/6/2020, 18:47:01] [HomeSeer] Host for ASCII Interface set to: IPADRESS at port 11000
Setup Payload:
X-HM://0024K9EMT8DN9
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
          
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 660-57-813 │     
    └────────────┘     
                       
[5/6/2020, 18:47:01] Error: listen EADDRINUSE: address already in use :::51100
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:85:21)
    at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:258:22)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:978:18)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:191:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:163:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:5)
[5/6/2020, 18:47:01] [HomeSeer] Successfully connected to ASCII Control Interface of HomeSeer.
[5/6/2020, 18:47:01] [HomeSeer] Sent Authorization Data
[5/6/2020, 18:47:01] Got SIGTERM, shutting down Homebridge...
[5/6/2020, 18:47:01] [HomeSeer] Successfully authorized Telnet port
```

Can you help me figure out what is wrong? 

Thanks

**Comment by malosaa** [comment]
Hi 

i just see your issue 
i did notice this : 
[5/6/2020, 18:47:01] Error: listen EADDRINUSE: address already in use :::51100

try to kill homebridge instance as that port is already in use or another instance is running

regards

**Comment by vegargrim** [comment]
Hi, and thanks for reply. I have tried killall homebridge and so on without luck. Do you have any commands that can help me with that?

**Comment by malosaa** [comment]
no worries, 
i really don't know other commands 

on what os are u running it ?
and what version are you using 

regards

**Comment by vegargrim** [comment]
im running on Raspbian GNU/Linux Buster (10) Node.js Version v12.16.3 Npm Version v6.14.4

Im using the official homebridge image

**Comment by justinfanok** [comment]
try
ps -ef | grep homebridge

then kill each by its PID, and try again

**Comment by vegargrim** [comment]
```
 ps -ef | grep homebridge
avahi      332     1  0 17:24 ?        00:00:03 avahi-daemon: running [homebridge.local]
pi        7513  7417  2 19:33 ?        00:00:01 homebridge
pi        7560   757  0 19:34 pts/0    00:00:00 grep --color=auto homebridge
```

I tried kill 332, 7513, and 7560. I considering doing a new clean install of homebridge

**Comment by jvmahon** [comment]
There have been a number of recent updates to homebridge. Maybe a clean install of homebridge and all plugins would help. On that point, see the following Wiki link which may help to identify and update the plugins to be deleted  and then re-installed : https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Problems-Updating-to-Version-1.0.0

**Comment by malosaa** [comment]
Hi vegargrim, 

if it still doesnt work go here and install this 
https://github.com/oznu/homebridge-config-ui-x
it works great, i did it yesterday and u can fully control every accessory and config trough the ui without going into other settings.

it shows the logs but also u can reset homebridge and other things without going into settings.

hope it helps

**Comment by jvmahon** [comment]
Since there was no further response, I'm assuming you got this working, or moved the question to the homebridge-config-ui-x github space as the issue seems to be with that plugin as far as I can tell.
